-m/M added (md5sum checking), colored error messages, bug fixes

diff --git a/boorutag b/boorutag
--- a/boorutag
+++ b/boorutag
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 #check for required commands, exit if failed
-required_commands=('xmllint' 'exiv2' 'curl')
+required_commands=('xmllint' 'exiv2' 'curl' 'md5sum')
 for cmd in "${required_commands[@]}"; do
 	if ! command -v ${cmd} >/dev/null 2>&1; then
 		missing_commands+=(${cmd})
@@ -9,7 +9,7 @@ for cmd in "${required_commands[@]}"; do
 done
 
 if (( ${#missing_commands[@]} > 0)); then
-	echo "Error: missing commands 
+	echo "${RED}ERROR:${NC} missing commands 
 	${missing_commands[@]}" >&2
 	exit 2
 fi
@@ -26,30 +26,34 @@ Example: boorutag -oU -S d -d ~/Pictures/homework
   !-d [dir]   run on all files of given directory
   -t [IX]     tag format to write [(I)PTC and/or (X)MP] (default: IX) 
   !-S [site]  search only in given site [(g)elbooru, (d)anbooru, (r)ule34]
-  !-r 	     disable reverse image search fallback
-  !-u 	     always download full-res image for samples if available
-  !-U 	     same as -u but OVERWRITES the image (its gone for good!)
-  -o	     overwrite existing tag/exif data
-  !-s	     silent mode (no output)
-  !-v	     verbose mode (more output)
-  -h	     display this help message" >&2;
+  -m	      generate and try matching against output of md5sum (THIS WILL WIPE EXIF DATA)
+  -M	      same as -m, but also renames the file to correct MD5 if match is found
+  !-r 	      disable reverse image search fallback
+  !-u 	      always download full-res image for samples if available
+  !-U 	      same as -u but OVERWRITES the image (its gone for good!)
+  -o	      overwrite existing tag/exif data
+  !-s	      silent mode (no output)
+  !-v	      verbose mode (more output)
+  -h	      display this help message" >&2;
 	exit 1
 }
 
-while getopts ":d:t:S:ruUosvh" opt; do
+while getopts ":d:t:S:mMruUosvh" opt; do
 	case $opt in
 		d) if [[ -d ${OPTARG} ]]; then directory=${OPTARG}; else
-			echo "Error: flag -d | directory '${OPTARG}' not found or invalid" >&2; exit 2; fi ;;
+			echo "${RED}ERROR:${NC} flag -d | directory '${OPTARG}' not found or invalid" >&2; exit 2; fi ;;
 		t) if ! [[ ${OPTARG} =~ ^([Ii]?[Xx]?$|^[Xx]?[Ii]?)$ ]]; then
-			echo "Error: flag -t | invalid option '${OPTARG}' - valid options are [I,X,IX]" >&2; exit 2; else
+			echo "${RED}ERROR:${NC} flag -t | invalid option '${OPTARG}' - valid options are [I,X,IX]" >&2; exit 2; else
 			tag_format="${OPTARG^^}"; fi ;;
 		S) shopt -s nocasematch
 			case ${OPTARG} in 
 				g|gelbooru) ;;
 				d|danbooru) ;;
 				r|rule34) ;;
-				*) echo "Error: flag -S | invalid option '${OPTARG}' | boorutag -h for usage" >&2; exit 2 ;;
+				*) echo "${RED}ERROR:${NC} flag -S | invalid option '${OPTARG}' | boorutag -h for usage" >&2; exit 2 ;;
 			esac; shopt -u nocasematch;;
+		m) gen_md5="1" ;;
+		M) gen_md5="2" ;;
 		r) reverse_fallback="0" ;;
 		u) always_upscale="1" ;;
 		U) always_upscale="2" ;;
@@ -57,12 +61,24 @@ while getopts ":d:t:S:ruUosvh" opt; do
 		s) silent="1" ;;
 		v) verbose="1" ;;
 		h) usage ;;
-		?) echo "Error: Invalid flag -$OPTARG" >&2; exit 2 ;;
-		:) echo "Error: -$OPTARG requires an argument" >&2; exit 2 ;;
+		?) echo "${RED}ERROR:${NC} Invalid flag -$OPTARG" >&2; exit 2 ;;
+		:) echo "${RED}ERROR:${NC} -$OPTARG requires an argument" >&2; exit 2 ;;
 	esac
 done
+if [[ $# -eq 0 ]]; then usage; fi
 shift "$(($OPTIND -1))"
 tag_format=${tag_format:-XI}
+
+RED='\033[1;31m'
+GREEN='\033[1;32m'
+YELLOW='\033[1;33m'
+NC='\033[0m'
+if [ ! -t 1 ]; then
+  RED=''
+  GREEN=''
+  YELLOW=''
+  NC=''
+fi
 
 
 CONFIG_DIR="${HOME}/.config/boorutag"
@@ -81,22 +97,34 @@ fi
 #base link for searches using md5
 gel_link="https://gelbooru.com/index.php?page=dapi&s=post&q=index${gelApi}&tags=md5:"
 
-#extract MD5 hash from filename if it exists, return 3 on fail
-#expects filename (basename)
+#extract MD5 hash from filename if it exists, return 1 on fail
+#expects file in
 getMD5 () {
-	local outMD5=$(grep -oP "[a-f\d]{32}" <<< $1)
-	if [[ -z ${outMD5} ]]; then 
-		echo "failed to find MD5 data of file $1" >&2
-		exit 3
-	else
-		echo ${outMD5}
+	local filename=$(basename $1)
+	local outMD5=$(grep -oP "[a-f\d]{32}" <<< $filename)
+	if [[ -n ${outMD5} ]]; then echo ${outMD5}; else
+		echo -e "${YELLOW}STATUS:${NC} failed to find MD5 data of file '$filename' in filename${gen_md5:+", trying from md5sum"}" >&2
+
+		if [[ ${gen_md5} -gt 0 ]]; then
+			exiv2 rm $1
+			outMD5=$(md5sum $1)
+			echo "${outMD5%% *}"
+			return 0
+		else return 1; 
+		fi
+
 	fi
 }
 
 #get xml from booru api and return tags
 fetchBooruData () {
 	local xml_result=$(curl --silent --request GET "${gel_link}$1")
-	echo $(xmllint --xpath '//tags/text()' - <<<${xml_result})
+	local xml_tags=$(xmllint --xpath '//tags/text()' - <<<${xml_result} 2>/dev/null )
+	if [[ $? -gt 0 || -z ${xml_tags} ]]; then 
+		return 1
+	else
+		echo ${xml_tags}
+	fi
 }
 
 # sample (low-res) detection
@@ -125,7 +153,7 @@ setTags () {
 	shift
 	local tags="$@"
 	#remove all exif, iptc, and xmp data
-	if [[ ${overwrite_tags} -eq "1" ]]; then exiv2 rm ${file}; fi
+	if [[ ${overwrite_tags} -eq 1 ]]; then exiv2 rm ${file}; fi
 
 	#iterate through tags and apply to IPTC 
 	if [[ $tag_format =~ I ]]; then
@@ -139,6 +167,18 @@ setTags () {
 		exiv2 -M "add Xmp.iptc.Keywords XmpBag ${tags// /, }" ${file}
 	fi
 
+	#rename file since proper md5 was generated if we made it this far
+	if [[ ${gen_md5} -eq 2 ]]; then 
+		local dir="${file%/*}"
+		[[ ${file} != */* ]] && dir=
+		local new="${dir:+$dir/}${MD5}.${file##*.}"
+		if [[ ${file} != ${new} ]]; then
+		  	mv ${file} ${new}
+			echo -e "${YELLOW}STATUS:${NC} renamed '${new}'"
+		fi
+	fi
+
+
 }
 
 declare -i progress
@@ -148,20 +188,23 @@ for f in "$@"; do
 
 	#check that file exists and is r/w capable
 	if ! [[ -r $f && -w $f ]]; then
-		echo "Error: read/write error on file '$f', skipping." >&2;
-		continue;
+		echo -e "${RED}ERROR:${NC} read/write error on file '$f', skipping." >&2
+		continue
 	fi
 
 	#skip file if tags exist and overwrite is disabled
 	if [[ $overwrite_tags -ne 1 && $(checkTags $f) ]]; then
-		echo "Tags exist for file '$f', skipping." >&2;
-		continue;
+		echo -e "${YELLOW}STATUS:${NC}: Tags exist for file '$f', skipping." >&2
+		continue
 	fi
 
-	Filename=$(basename $f)
-	MD5=$(getMD5 ${Filename})
-	Tags=$(fetchBooruData ${MD5})
+	MD5=$(getMD5 $f)
+	if Tags=$(fetchBooruData ${MD5}); then 
+		setTags $f ${Tags}
+	else
+		echo -e "${RED}ERROR:${NC} failed to retrieve tags for '$f', skipping" >&2
+		continue
+	fi
 	# sampleCheck $f
-	setTags $f ${Tags}
 	sleep 0.1 #good enough for rate limiting :3
 done
